[package]
name = "maprando-plando-update"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.68", features = ["backtrace"] }
reqwest = { version = "0.12.15" }
self_update = "0.42.0"
#sysinfo = "0.37.0"
zip = "4.0.0"
